### ISSUE TITLE
Maps appear off screen

### ISSUE THREAD

**Issue by Brewmaj** [nomns/nparse#66] opened 2023-10-25 17:23 UTC
I have three monitors, but this issue appears even if I disconnect all but one. The Maps will appear off screen. I can see it on my toolbar, but not on the screen. I tried Alt-Space and M (for Move), but I can't move the Maps window. There were other times where a portion of the Maps window was visible, but I could not drag it down, or change the size because the button to make the Maps window was not on the screen. I've had limited success when I could see a portion by going into my Display settings and changing the Advanced display settings - either resolution or refresh from 60 to 59.9.

**Comment by Belwri** [comment] 2024-01-24 12:30
this is happening to me. Did you ever find a solution? PoM tricky with no maps lol

**Comment by rm-you** [comment] 2024-04-15 16:38
This usually happens when your display size/orientation or the number of displays you have connected has changed since you configured the position of the window. You can reset the position by editing the config file and removing the geometry section from the map section in the json. It will go back to 0,0 which is typically always visible. You can also change the location there to any arbitrary point you know you want the window to appear. Just make sure nparse is closed before you edit the config.

**Comment by Brewmaj** [comment] 2024-04-15 19:41
I found a work around where I edit the .json file under the "maps" and "geometry": section as follows (for a standard monitor):
"geometry": [
            -800,
            1582,
            265,
            512

**Comment by rm-you** [comment] 2024-04-19 06:15
Yeah, that will work, as will removing the section entirely which will regenerate it at 0,0 (easier for a lot of less technical folks). I could possibly put a reset button in the settings menu somewhere, just to make this easier... Will leave this open for now and consider if there's any way to do off-screen detection.

**Comment by rm-you** [comment] 2024-04-19 06:18
Ah, technically this is a duplicate of issue #43 so closing this and will handle it there!

**Closed by rm-you** 2024-04-19 06:18 UTC
Labels: enhancement
