### ISSUE TITLE
"Untitled exception in script"

### ISSUE THREAD

**Issue by MaxPlanck12** [nomns/nparse#53] opened 2022-11-19 00:55 UTC
Just tried installing, but when I am trying to run the .exe I'm getting an "Untitled exception in script" error.  Any ideas of what could be wrong?

**Comment by rm-you** [comment] 2024-04-19 06:22
Duplicate of #63 (which was posted later but has more clear info so treating it as the main issue).

**Closed by rm-you** 2024-04-19 06:22 UTC
