### ISSUE TITLE
[Feat Req] Remember window positions/size + checked modules

### ISSUE THREAD

**Issue by dylanh724** [nomns/nparse#58] opened 2023-02-10 02:19 UTC
Whenever I restart nParse, I have to:

1. Right click nparse >> spells >> maps
2. Move the windows to my 2nd screen
3. Resize my windows
4. "Set" both [|||]

Worthwhile, but tedious! **Please remember my:**

1. Active modules (eg: Spells, Map)
2. Window positions

Thank you!! Amazing app.

**Comment by That-one-Joe** [comment] 2023-02-15 21:15
Actually, it is being saved. Works for me on all my PCs.

The question would be, why isn't it for you? Are you exiting nParse regularly? Does it have write permissions (nparse.config.json)?

**Comment by rm-you** [comment] 2024-04-15 17:05
As the other commenter said, it should be saving these settings. The only reason I can think that it wouldn't is if nparse is never closed properly (crashes, or the process is killed), or the process doesn't have write access to the config file or the directory it is in.

**Comment by rm-you** [comment] 2024-04-19 06:20
Marking this as invalid for now as I believe this is an issue occuring due to something on the user's side -- if you can explain how to reproduce this I am happy to re-open the issue!

**Closed by rm-you** 2024-04-19 06:20 UTC
Labels: invalid
